uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE139566
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE155887
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE169196
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE174635
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE179401
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE180296
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE184009
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE190105
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE195964
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE196463
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE198867
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE198868
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE199413
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE200291
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE208113
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE210592
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE212521
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE214378
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE214960
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE216571
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE217245
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE218730
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE226327
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE226335
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE226336
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE234668
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE234673
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE237266
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE245991
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE246602
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE249283
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE250205
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE255242
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE255321
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE259383
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE260674
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE264122
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE264650
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE265780
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE273484
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE277096
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE280954
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE281102
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE281646
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE282589
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE283144
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE283145
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE288118
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE288132
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE290982
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE292297
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE292621
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE294241
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE301286
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE301287
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE302797
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE309028
uv run python -m agent.cli --output-dir out/bsAb/ --config ./config/gat-llama3-8b-it_config.yaml --gse GSE309061
